
START_TIME          = 0  

ARPEGGIO_TRACK      = 0
ARPEGGIO_CHANNEL    = 0

PERCUSSION_TRACK    = 1
PERCUSSION_CHANNEL  = 10

PROGRESSION_TRACK   = 2
PROGRESSION_CHANNEL = 2

LEAD_TRACK          = 3
LEAD_CHANNEL        = 3